# Generated by Django 5.2.5 on 2025-09-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=20)),
                ('jumlah', models.IntegerField()),
                ('kategori', models.CharField(blank=True, max_length=20, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barang',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nuptk', models.CharField(max_length=20, unique=True)),
                ('nama_guru', models.CharField(max_length=30)),
                ('bidang', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pegawai', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nama_pegawai', models.CharField(max_length=30)),
                ('bidang', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pegawai',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nis', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nama_siswa', models.CharField(max_length=30)),
                ('kelas', models.CharField(blank=True, max_length=15, null=True)),
                ('kartu_pelajar', models.BinaryField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_pinjam', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tanggal_pinjam', models.DateTimeField()),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True)),
                ('status_pinjam', models.TextField(blank=True, null=True)),
                ('id_pegawai', models.ForeignKey(blank=True, db_column='id_pegawai', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pegawai')),
                ('nuptk', models.ForeignKey(blank=True, db_column='nuptk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.guru')),
                ('nis', models.ForeignKey(blank=True, db_column='nis', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.siswa')),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_detail', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('jumlah', models.IntegerField()),
                ('waktu_pengambilan', models.DateTimeField(blank=True, null=True)),
                ('batas_ambil', models.DateTimeField(blank=True, null=True)),
                ('status_pengambilan', models.TextField(blank=True, null=True)),
                ('id_barang', models.ForeignKey(db_column='id_barang', on_delete=django.db.models.deletion.DO_NOTHING, to='api.barang')),
                ('id_peminjaman', models.ForeignKey(db_column='id_peminjaman', on_delete=django.db.models.deletion.DO_NOTHING, to='api.peminjaman')),
            ],
            options={
                'db_table': 'detail_peminjaman',
            },
        ),
    ]
