# Generated by Django 5.2.5 on 2025-09-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=20)),
                ('jumlah', models.IntegerField()),
                ('kategori', models.CharField(blank=True, max_length=20, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('kode_detail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField()),
                ('waktu_pengambilan', models.DateTimeField(blank=True, null=True)),
                ('batas_ambil', models.DateTimeField(blank=True, null=True)),
                ('status_pengambilan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_peminjaman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('nuptk', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_guru', models.CharField(max_length=30)),
                ('bidang', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'guru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(max_length=30)),
                ('bidang', models.CharField(blank=True, max_length=20, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pegawai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('kode_pinjam', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateTimeField()),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True)),
                ('status_pinjam', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peminjaman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_siswa', models.CharField(max_length=30)),
                ('kelas', models.CharField(blank=True, max_length=15, null=True)),
                ('kartu_pelajar', models.BinaryField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'siswa',
                'managed': False,
            },
        ),
    ]
